### PR TITLE
Add tomcat8 directory to project structure section of README.md

### PR DESCRIPTION
**Pull request by breser**

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by rhusar** [comment]
This is ok to test.

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 690bcbc4c6a853a6bb397b4fbb9e2332abb7e3d9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 157 outcome was SUCCESS using a merge of 690bcbc4c6a853a6bb397b4fbb9e2332abb7e3d9 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/157
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/157

**Pull request merged**
