### PR TITLE
Fix 1.3.x

### PR DESCRIPTION
**Pull request by jfclere**
Various fixes back ported or cherry-picked from https://github.com/modcluster/mod_proxy_cluster

### CODE REVIEW

**Comment by rhusar** [comment]
@jfclere Needs a rebase after last push for some reason.

**Comment by jfclere** [comment]
@rhusar rebased

**Comment by rhusar** [comment]
@jfclere Can you please only reference https://issues.jboss.org/browse/MODCLUSTER issues in the commits as for the reasons mentioned on the call last Thursday? i.e. please clone JBCS-729 into the MODCLUSTER tracker.

**Comment by jfclere** [comment]
Should be good now...

**Pull request merged**
