### PR TITLE
Fixes deterministic failover capability for 1.3.x [MODCLUSTER-590] [MODCLUSTER-675] [MODCLUSTER-697]

### PR DESCRIPTION
**Pull request by Karm**
Signed-off-by: Michal Karm Babacek <karm@email.cz>

### CODE REVIEW

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
Travis can be ignored, it runs Java. This is native commit.

Passed Windows build:  https://ci.modcluster.io/job/mod_cluster-1.3.x-windows/6/

**Comment by rhusar** [comment]
@Karm please link upstream PRs, thanks!

**Comment by rhusar** [comment]
@Karm Please link issue ID in the commit message.

**Comment by Karm** [comment]
> @Karm please link upstream PRs, thanks!
Cannot do that. [Upstream master got pushed into directly](https://github.com/modcluster/mod_proxy_cluster/commit/0ff923bcb4c789df8fb66ffe9b04be0af70acefd) without PR...

> @Karm Please link issue ID in the commit message.

Amended.

**Comment by Karm** [comment]
@rhusar  Is there any way you can *disable* travis for changes in ```native``` subdirectory?

BTW Jenkins CI on natives works, it runs the build with the PR, but for some reason it does not comment here. Gonna investigate why.   The flow works GitHub - > Jenkins but not Jenkins -> GitHub

**Comment by rhusar** [comment]
>> @Karm please link upstream PRs, thanks!

> Cannot do that. Upstream master got pushed into directly without PR...

@jfclere Please always use the pull request facility for changes :-(

**Comment by rhusar** [comment]
@Karm I don't think there is such a feature on Travis CI. I will fix the CI.

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
@rhusar @jfclere  Jenkins communication to GitHub restored.

**Comment by msfm** [comment]
Could you please also add JIRA ID MODCLUSTER-697 in the commit message?

**Comment by Karm** [comment]
@msfm Amended.

**Comment by Karm** [comment]
@jfclere Requested
 - removal of .gitignore changes
 - splitting declaration and assignment

Amended.

**Comment by rhusar** [comment]
Awesome job, thanks guys.

**Pull request merged**
