### PR TITLE
MODCLUSTER-823: Fix ignored aliases

### PR DESCRIPTION
**Pull request by jajik**
Backport of https://github.com/modcluster/mod_proxy_cluster/pull/239

### CODE REVIEW

**Comment by jajik** [comment]
Upstream merged, marking Ready for review.

**Review by jfclere — APPROVED** [review]

**Comment by jajik** [comment]
Thanks, merging

**Comment by rhusar** [comment]
@jajik Don't forget to update Jira when merging - especially to 1.3.x branch - https://issues.redhat.com/browse/MODCLUSTER-823

**Comment by jajik** [comment]
Will do, on Monday

**Pull request merged**
