### PR TITLE
https://issues.redhat.com/browse/MODCLUSTER-736 "fix" for JBCS-1236

### PR DESCRIPTION
**Pull request by jfclere**
Add assert to restart the process and prevent the need of httpd restart

### CODE REVIEW

**Comment by rhusar** [comment]
@jfclere Who can we get to review? Please nominate.

**Review by dsartzet — APPROVED** [review]

**Comment by rhusar** [comment]
@dsartzet Thanks, merging then ;-)

**Comment by rhusar** [comment]
@jfclere Does this require fix in 2.0 - https://github.com/modcluster/mod_proxy_cluster?

**Comment by jfclere** [comment]
@rhusar probably yes: There is the same logic near https://github.com/modcluster/mod_proxy_cluster/blob/main/native/mod_proxy_cluster/mod_proxy_cluster.c#L628

**Comment by rhusar** [comment]
@jfclere Can you please submit a PR or link a tracker at least? So that this doesn't fall through the cracks.

**Pull request merged**
