### PR TITLE
[MODCLUSTER-397] potential fix for ProxyPass stickysessions issue

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.jboss.org/browse/MODCLUSTER-397

### CODE REVIEW

**Comment by Karm** [comment]
@jfclere @aogburn Any news on this one?

**Comment by aogburn** [comment]
See https://github.com/modcluster/mod_cluster/pull/158 for a master PR using notes to avoid additional table reads.  If it checks out, I can port it for 1.2 as well (although it probably wouldn't ever see an official 1.2 release?)

**Comment by Karm** [comment]
@aogburn @jfclere Why wouldn't it?

**Comment by aogburn** [comment]
@Karm it wouldn't with EAP 6 at least as EAP 6.4/mod_cluster 1.2.11.Final was the last release there (we don't release new natives with EAP 6 cps)

**Comment by Karm** [comment]
Heads up: @jfclere @aogburn We are about to patch & release 1.2.13.  :package:

**Comment by Karm** [comment]
@aogburn @jfclere Closing. Superseded by https://github.com/modcluster/mod_cluster/pull/188 that combines both the original functional idea and the latter optimization from https://github.com/modcluster/mod_cluster/pull/158

Cheers
-K-

**Pull request closed without merging**
