### PR TITLE
MODCLUSTER-561 Upgrade maven-war-plugin to version compatible with JDK 9

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/MODCLUSTER-561
https://issues.jboss.org/browse/MODCLUSTER-586

Now mod_cluster builds on JDK9 including the demo!

### CODE REVIEW

**Comment by Karm** [comment]
Merged 🙈

**Comment by rhusar** [comment]
@Karm bit of a premature merge. All fixes required for support branches need to be merged before upstream can be merged. Since we need to support JDK9 for 1.3 branch, it needs to be merged first.

**Comment by rhusar** [comment]
Opened https://github.com/modcluster/mod_cluster/pull/259 for 1.3.

**Comment by rhusar** [comment]
Also, Jiras need to be resolved upon merge.

**Comment by rhusar** [comment]
Ok, the mess  is cleaned up now.

**Comment by Karm** [comment]
@rhusar  O.K. THX.

This caught my eye though:
> Since we need to support JDK9 for 1.3 branch

Hmm, do we? I was under the impression we were going to release 2.0.0.Final for
* Tomcat 8.5
* Wildfly 11.something

but from your comment, it seems we are stuck on 1.3.x until

* Tomcat 9
* Wildfly 12

Could you elaborate more? Perhaps in an article on JBoss forum?

**Comment by Karm** [comment]
@rhusar 

Ad 
> All fixes required for support branches need to be merged

Fix version/s field needs updating I guess:
https://issues.jboss.org/browse/MODCLUSTER-586

**Comment by rhusar** [comment]
> Fix version/s field needs updating I guess:
> https://issues.jboss.org/browse/MODCLUSTER-586

No, this was not backported as its not needed

**Comment by rhusar** [comment]
> Hmm, do we? I was under the impression we were going to release 2.0.0.Final for
I am afraid we don't have a concrete timeline yet.

**Pull request merged**
