### PR TITLE
[MODCLUSTER-469] reset jvmRoute in context when generated dynamically…

### PR DESCRIPTION
**Pull request by zerikv**
https://issues.jboss.org/browse/MODCLUSTER-469

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by rhusar** [comment]
This is OK to test.

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of a2b4f6acfb3471300cd7f2896bd25c7c583680b3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 158 outcome was SUCCESS using a merge of a2b4f6acfb3471300cd7f2896bd25c7c583680b3 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/158
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/158

**Comment by rhusar** [comment]
Thanks @zerikv, I have commented on https://issues.jboss.org/browse/MODCLUSTER-469.

Closing the PR as this is certainly not the approach to extend the generic SPI interfaces to do container specific fix (also would need a rebase by now).

**Comment by rhusar** [comment]
Replaced by https://github.com/modcluster/mod_cluster/pull/303

**Pull request closed without merging**
