### PR TITLE
Fix for https://issues.redhat.com/browse/MODCLUSTER-750

### PR DESCRIPTION
**Pull request by jfclere**
https://issues.redhat.com/browse/MODCLUSTER-750
Upstream commit https://github.com/modcluster/mod_proxy_cluster/commit/c3f8b81f4b88766ff9eaaeaa88b287f8dae225fd
doc: https://github.com/modcluster/docs.modcluster.io/blob/main/docs/src/main/asciidoc/native.adoc#responsefieldsize

### CODE REVIEW

**Comment by rhusar** [comment]
@jfclere To move this forward:

1. Please assign a reviewer from EWS team.
2. Please link documentation PR (https://github.com/modcluster/docs.modcluster.io)
3. Please link upstream PR or indicate if not required.

Thanks!

**Comment by rhusar** [comment]
@sgala Any ETA on the review? Thanks.

**Review by sgala — APPROVED** [review]
Looks good to me

**Comment by sgala** [comment]
@rhusar Sorry for the delay, I missed the notifications...

**Comment by rhusar** [comment]
Back from PTO – Thanks @sgala @jfclere  !

**Pull request merged**
