### PR TITLE
MODCLUSTER-463 converts aliases for a context on -APP message arrival.

### PR DESCRIPTION
**Pull request by Karm**
See [MODCLUSTER-463](https://issues.jboss.org/browse/MODCLUSTER-463) for details.

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 2e86dfaf1d0bee475e5e27867705c87e45460065 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 151 outcome was SUCCESS using a merge of 2e86dfaf1d0bee475e5e27867705c87e45460065 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/151
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/151

**Comment by rhusar** [comment]
I may be reading this wrong, but this sounds like complete violation of RFC recommendation:

{quote}
When data enters the domain system, its original case should be preserved whenever possible. 
{quote}

rfc1035#section-2.3.3, 2nd paragraph

**Comment by jfclere** [comment]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.2 might what Michal is following.

**Comment by Karm** [comment]
@rhusar We ain't no *domain system*, we are a mere consumer, client. As I explained on [MODCLUSTER-463](https://issues.jboss.org/browse/MODCLUSTER-463), all JBossWeb versions report aliases in *lower case*, regardless of what one actually configures in AS5/AS7/Tomcat6/Tomcat7/Tomcat8. So, it is a historical thing that emerges from mod_proxy origins; it is not a simple mod_cluster bug. 

The alias comparing case-in/sensitivity cuts deeper [than this simple comparison](https://github.com/modcluster/mod_cluster/blob/master/native/mod_proxy_cluster/mod_proxy_cluster.c#L3013). It is not enough to fix this bit.

@jfclere Ad [RFC 2616 Section 3.2.2](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.2), yes, I've read it while I was googling for [RFC1035 Section 2.3.3](https://tools.ietf.org/html/rfc1035#section-2.3.3). IMHO one is not obliged to store host names verbatim.

# Conclusion
* Up until Undertow, no mod_cluster enabled *worker side* system has ever sent upper case/:camel: case Alias.
* If you are convinced that we should hunt down all literal, byte-to-byte  (i.e. wrong) comparisons and fix them; calling ```apr_tolower``` on every single byte of every vhost(alias) string every time; I can give it another shot and take a look at what would need to be patched.
* IMHO, we do not violate anything with not remembering the original Alias string case.
* On the contrary, the fact that we would display it case-sensitively on the mod_cluster manager page could lure users into thinking that Aliases are actually case-sensitive.
* Lemme know...

**Comment by Karm** [comment]
Master is not the right place in this repo any more. See:
1.2.x PR: https://github.com/modcluster/mod_cluster/pull/185
1.3.x PR: https://github.com/modcluster/mod_cluster/pull/182
master in mod_cluster 2.0: mod_proxy_cluster repo: TBD... probably tomorrow.

**Pull request closed without merging**
