### PR TITLE
Fix for MODCLUSTER-680.

### PR DESCRIPTION
**Pull request by jfclere**
See http://tomcat.apache.org/tomcat-9.0-doc/config/http.html#Standard_Implementation looks for SSLEnabled.

### CODE REVIEW

**Comment by rhusar** [comment]
@Karm @jfclere Do you think we need a backport to 1.x?

**Comment by jfclere** [comment]
Yes please.

**Comment by rhusar** [comment]
1.4 PR - https://github.com/modcluster/mod_cluster/pull/369

Do we need this for older branches? I wouldn't think so. Let me know.

**Comment by jfclere** [comment]
We don't need the older branches.

**Comment by rhusar** [comment]
👍

**Pull request merged**
