### PR TITLE
[MODCLUSTER-397] StickySessions don't work for ProxyPass from unenabled context

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.jboss.org/browse/MODCLUSTER-397

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 57f3a9826e10b8cfde96ff578b867b2a80ee3ef8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 154 outcome was SUCCESS using a merge of 57f3a9826e10b8cfde96ff578b867b2a80ee3ef8 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/154
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/154

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 5b42ef32fddd6a3eb4dde73453044e94273d6025 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 159 outcome was SUCCESS using a merge of 5b42ef32fddd6a3eb4dde73453044e94273d6025 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/159
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/159

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 35e6d1e17ba1123186b180263b0a8df83d377855 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 160 outcome was SUCCESS using a merge of 35e6d1e17ba1123186b180263b0a8df83d377855 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/160
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/160

**Comment by Karm** [comment]
@jfclere @aogburn Guys, any news here? It appears the issue is somewhat hanging in a limbo.

**Comment by jfclere** [comment]
Do we want that logic controlled by a directive? It breaks the compatibility that is why I am asking.

**Pull request merged**
