### PR TITLE
Fix for MODCLUSTER-521.

### PR DESCRIPTION
**Pull request by jfclere**

### CODE REVIEW

**Comment by Karm** [comment]
Discussion unravels on [MODCLUSTER-521](https://issues.jboss.org/browse/MODCLUSTER-521?focusedCommentId=13255996&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13255996).

TL;DR: My MSVC 19 compiles it without complains both with and without ```-Wdeclaration-after-statement```...so good news it that it compiles, bad news is that older MSVC might still complain.

**Comment by Karm** [comment]
@jfclere I suggest merging it.

**Comment by jfclere** [comment]
It is know as BZ1346877 too.

**Comment by rhusar** [comment]
@jfclere Just to state the obvious, we can add BZ numbers to commit messages (if they exist) otherwise we can just link from BZ to here/commit.

**Pull request merged**
