### PR TITLE
[1.2] MODCLUSTER-430, Re-creating proxy_module configuration structures in ord...

### PR DESCRIPTION
**Pull request by Karm**
...er to have them unique, not being shared with the main_server. Furthermore, some minor httpd 2.2.x compatibility fix and additional logging. See [pull/119](https://github.com/modcluster/mod_cluster/pull/119) for details...

### CODE REVIEW

**Comment by rhusar** [comment]
Needs a rebase.

**Comment by rhusar** [comment]
Linking PR to previous master PR (now closed as needs to be resubmitted): https://github.com/modcluster/mod_cluster/pull/119.

**Comment by antoineco** [comment]
@Karm in the linked original issue you mentioned your tests were successful. What's the current status of this PR?

**Comment by jfclere** [comment]
Need to be rebased and won't be done in mod_cluster but in mod_proxy_cluster

**Pull request closed without merging**
