### PR TITLE
MODCLUSTER-456 Upgrade build to JDK 7

### PR DESCRIPTION
**Pull request by rhusar**
https://issues.jboss.org/browse/MODCLUSTER-456

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 994033d15aed688c14d065227f51eeff9403e091 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by rhusar** [comment]
The CI job uses JDK 7 already.

**Comment by modcluster-pull-request** [comment]
Build 141 outcome was SUCCESS using a merge of 994033d15aed688c14d065227f51eeff9403e091 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/141
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/141

**Comment by rhusar** [comment]
We will postpone this and will have to revalidate implications for Tomcat 6.

**Comment by rhusar** [comment]
We have decided not to take this approach. Updated the Jira to fix compilation on JDK6, closing this.

**Pull request closed without merging**
