### PR TITLE
MODCLUSTER-479 Add support for Tomcat 9

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/MODCLUSTER-479

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 186d224ccbd2f5305453573a87f519cfab58c633 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 176 outcome was FAILURE using a merge of 186d224ccbd2f5305453573a87f519cfab58c633 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/176
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/176

**Comment by rhusar** [comment]
CI is using JDK7 which cannot work with Tomcat 8. Switched it now.

**Comment by rhusar** [comment]
retest this please

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of c71f197860dd05ea6a1841b2f6765a8b205590a0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 177 outcome was SUCCESS using a merge of c71f197860dd05ea6a1841b2f6765a8b205590a0 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/177
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/177

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 23ef199c8eebd3e9d1961894da562c37c0039673 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 178 outcome was SUCCESS using a merge of 23ef199c8eebd3e9d1961894da562c37c0039673 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/178
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/178

**Comment by rhusar** [comment]
Successfully manually tested on Tomcat M4, ready to go. @pferraro @jfclere

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 71c27a2c0d97f9de5ed3195b069171981ac85f72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 179 outcome was SUCCESS using a merge of 71c27a2c0d97f9de5ed3195b069171981ac85f72 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/179
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/179

**Comment by jfclere** [comment]
Could you please fix the conflicts (created by me merging #176

**Comment by rhusar** [comment]
Rebased, tests should be running shortly.

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of d36b3fb429bcf35aa28be611c8fa045c32e36790 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 181 outcome was SUCCESS using a merge of d36b3fb429bcf35aa28be611c8fa045c32e36790 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/181
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/181

**Pull request merged**
