### PR TITLE
Make it actually runnable

### PR DESCRIPTION
**Pull request by NKame**

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by rhusar** [comment]
This is ok to test.

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of b6375ce7921664a39ba2483d65f7a26176756281 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 162 outcome was SUCCESS using a merge of b6375ce7921664a39ba2483d65f7a26176756281 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/162
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/162

**Pull request merged**
