### PR TITLE
[1.3] Backporting fix for MODCLUSTER-722

### PR DESCRIPTION
**Pull request by gzaronikas**
1.3.x backport of https://github.com/modcluster/mod_proxy_cluster/pull/29 for fixing https://issues.redhat.com/browse/MODCLUSTER-722

### CODE REVIEW

**Comment by rhusar** [comment]
run tests

**Comment by gzaronikas** [comment]
@rhusar unfortunately as long as w2012 is down on CI, tests will be stuck on pending :(

**Comment by rhusar** [comment]
@gzaronikas Can you look into it? This was managed by Michal and I am not familiar with what needs to happen here. It would be ideal if we could have this be built with GitHub actions (like upstream master is now).

**Comment by Karm** [comment]
@gzaronikas  @rhusar 
Ad w2k12: The box is dead. I was given a replacement VM yesterday. Might find some time next week to install it.

Ad GitHub actions: Yes, it can work. There is Visual Studio available. It is dead simple to compile mod_cluster natives on their own.   Need for more dependencies arise with other libs, sch as OpenSSL, apr, iconv, pcre, nghttp and httpd itself. One needs to install Perl and NASM...   

I will bring another Windows box to the Jenkins.   I won't, due to time-resource limitations, do anything about GitHub Workflows for this project though.

**Comment by jfclere** [comment]
Was merged in JBCS repo.

**Pull request merged**
