### PR TITLE
[JBCS-634] decrease loops per vhosts for balancer changes

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.jboss.org/browse/JBCS-634

### CODE REVIEW

**Comment by Karm** [comment]
@aogburn Can you open it with https://github.com/modcluster/mod_proxy_cluster too, please?

**Comment by aogburn** [comment]
@Karm sure, see https://github.com/modcluster/mod_proxy_cluster/pull/23

**Comment by rhusar** [comment]
@jfclere  Upstream has been merged, but not downstream – what's your intention here?

**Comment by jfclere** [comment]
Actually the patch doesn't work as expected - DON'T merge it causes 503 (creation and removal of workers is asymmetric with the patch).

**Comment by jfclere** [comment]
@Karm please check the test. I would like to merge the PR.

**Pull request merged**
