### PR TITLE
1.3.x

### PR DESCRIPTION
**Pull request by jfclere**
Fixes related to JBCS-729.

### CODE REVIEW

**Comment by rhusar** [comment]
Any reason why these are not git cherry-pick -ed?

**Comment by jfclere** [comment]
They come from https://github.com/modcluster/mod_proxy_cluster

**Comment by rhusar** [comment]
@jfclere Its the same repo root, they can be cherrypicked no problem...

**Comment by jfclere** [comment]
I have opened a new one...

**Pull request closed without merging**
