### PR TITLE
Various small things.

### PR DESCRIPTION
**Pull request by jfclere**
Note that the most problematic one is BZ 822250.

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 3dcafd6a551236d7a4500d2af792fcdd6ae9ebf1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 135 outcome was SUCCESS using a merge of 3dcafd6a551236d7a4500d2af792fcdd6ae9ebf1 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/135
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/135

**Comment by Karm** [comment]
Squash would be lovely :-P

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 864a6fae6acb8ca39ecccb0ba4f4ab4feb4f739a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by jfclere** [comment]
On 02/16/2015 06:03 PM, Michal Karm Babacek wrote:
> Squash would be lovely :-P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modcluster/mod_cluster/pull/139#issuecomment-74540094>.
>

Done :D

**Comment by modcluster-pull-request** [comment]
Build 136 outcome was SUCCESS using a merge of 864a6fae6acb8ca39ecccb0ba4f4ab4feb4f739a on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/136
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/136

**Pull request merged**
