### PR TITLE
Introduce end-of-line normalization

### PR DESCRIPTION
**Pull request by rhusar**
Let's do this to put @pferraro 's concerns to an end?

Some read here http://git-scm.com/docs/gitattributes

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 8410591b600a9e507fef228eb7fe970be9030ae2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 145 outcome was FAILURE using a merge of 8410591b600a9e507fef228eb7fe970be9030ae2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/145
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/145

**Comment by rhusar** [comment]
Also testing the CI job here, so the failure is anticipated, sorry for noise.

**Comment by rhusar** [comment]
Retest this please. 

PS: Switching CI job back to JDK7 due to Tomcat 8

**Comment by rhusar** [comment]
Retest this please.

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 8410591b600a9e507fef228eb7fe970be9030ae2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 147 outcome was SUCCESS using a merge of 8410591b600a9e507fef228eb7fe970be9030ae2 on branch master:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/147
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/147

**Pull request merged**
