### PR TITLE
[1.3] CI updates

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by Karm** [comment]
@rhusar Travis says no....

**Comment by Karm** [comment]
Besides - I would very much like to see this branch excluded.

Java lives in master and 1.4.x     

1.3.x is for natives....

**Comment by Karm** [comment]
Or at least exclude native/* directory.

**Comment by rhusar** [comment]
Doesn't seem to be possible ATM.

**Comment by rhusar** [comment]
@Karm Also we wanted to change the job name from "default" and update the integration to use https://github.com/modcluster-pull-request bot.

**Comment by Karm** [comment]
@rhusar It uses  a bot - [KarmBot](https://github.com/KarmBot).   We can change bot for bot though :)

**Pull request merged**
