### PR TITLE
[MODCLUSTER-397] StickySessions don't work for ProxyPass from unenabl…

### PR DESCRIPTION
**Pull request by Karm**
…ed context
* brings @aogburn 's patch for [MODCLUSTER-397](https://issues.jboss.org/browse/MODCLUSTER-397) into 1.2.x branch

# Tested
```
CreateBalancers 1

ProxyPass "/" "balancer://mycluster/clusterbench/requestinfo" stickysession=JSESSIONID|jsessionid nofailover=On
ProxyPassReverse  "/" "balancer://mycluster/clusterbench/requestinfo"
ProxyPassReverseCookiePath  "/clusterbench"  "/"
```
* one balancer
* two tomcats, deployed *clusterbench* each

## Before
Erratic behaviour, doesn't keep session stickiness: [see log](https://gist.github.com/Karm/66c49e601ffd8727e451a1c1fb6d66a6)

## After
Rock solid, keeps sticky sessions: [see log](https://gist.github.com/Karm/76fb91007ae9b9ede62acc8b4914a76c)

Cheers
-K-

### CODE REVIEW

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of 2e7a4f8af55dc27e31e8da0dd047658ad0423e9e on branch 1.2.x:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Comment by modcluster-pull-request** [comment]
Build 189 outcome was SUCCESS using a merge of 2e7a4f8af55dc27e31e8da0dd047658ad0423e9e on branch 1.2.x:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/189
Public: https://hudson.jboss.org/hudson/job/mod_cluster-1.3.x-pull-player-executor/189

**Comment by jfclere** [comment]
you need  to fix some variable declarations in the code like:
https://github.com/modcluster/mod_cluster/pull/188/commits/2e7a4f8af55dc27e31e8da0dd047658ad0423e9e#diff-b0880ea8cdee300885bd1c5ae7f4cebbR3105

**Comment by jfclere** [comment]
I guess we need a master PR too.

**Comment by Karm** [comment]
@jfclere Well, O.K. I'll. Still, could you explain why exactly is it wrong? It's not C89, but it's perfectly fine C99. Variable should be declared as locally as possible. Even my MSVC from VS 2014 handles these C99 style declarations fine...  Maybe I'm looking in a wrong direction though.

**Comment by jfclere** [comment]
It won't compile on some boxes so please fix it.

**Comment by Karm** [comment]
@jfclere  [Fixed](https://github.com/modcluster/mod_cluster/pull/188/files#diff-b0880ea8cdee300885bd1c5ae7f4cebbR3061) to comply with the coding standard.

**Comment by modcluster-pull-request** [comment]
Triggering build using a merge of e45dd9b6f30b140541c9475a13337784644edc76 on branch 1.2.x:
Private: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/mod_cluster-1.3.x-pull-player-executor/

**Pull request merged**
